sudo: required
dist: trusty
addons:
  chrome: stable
language: node_js
node_js:
  - 11.10.0
before_install:
  - echo "$TRAVIS_BRANCH"
  - echo "$TRAVIS_PULL_REQUEST"
  - npm i npm -g
  - npm install -g greenkeeper-lockfile@1
  - cd src/ngx-tabset
install:
  - npm install
script:
  - npm run test
  - npm run build
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - greenkeeper-lockfile-update
after_script:
  - greenkeeper-lockfile-upload
after_success:
  - codecov
  - rm -r node_modules
  - cd ../..
  - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == false ]; then npm run ghpages; fi
notifications:
  email: false
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist
  github_token: $PUSH_TOKEN
  on:
    branch: master
